#include <windef.h>
#include "CommissionData.h"

#ifndef COMMISSION_EMULATOR_CONFIG_H
#define COMMISSION_EMULATOR_CONFIG_H


#define URGENT_COMMISSION_GET_PER_MINUTE 0.05

#define EMULATE_DAYS 1000000

static INT FilterTag[] = {
        GEM_8_FILTER,
        GEM_4_FILTER,
        GEM_2_FILTER,
        DAILYCHIP_1_FILTER,
        DAILYCHIP_2_FILTER,
        EXTRACUBE_0_30_FILTER,
        DAILYRESOURCE_1_FILTER,
        DAILYRESOURCE_2_FILTER,
        URGENTCUBE_1_30_FILTER,
        URGENTCUBE_1_45_FILTER,
        URGENTCUBE_3_FILTER,
        URGENTCUBE_2_15_FILTER,
        URGENTBOX_6_FILTER,
        URGENTBOX_3_FILTER,
        URGENTBOX_1_FILTER,
        URGENTCUBE_4_FILTER,
        EXTRACUBE_1_30_FILTER,
        EXTRACUBE_3_FILTER,
        URGENTCUBE_6_FILTER,
        EXTRAOIL_8_FILTER,
        EXTRADRILL_5_20_FILTER,
        EXTRADRILL_3_20_FILTER,
        EXTRAOIL_4_FILTER,
        EXTRADRILL_2_FILTER,
        EXTRAOIL_1_FILTER,
        URGENTDRILL_1_30_FILTER,
        EXTRADRILL_0_20_FILTER,
        EXTRADRILL_1_FILTER,
        URGENTDRILL_4_FILTER,
        URGENTDRILL_1_FILTER,
        URGENTDRILL_2_40_FILTER,
        SHORTEST_FILTER
};



#endif //COMMISSION_EMULATOR_CONFIG_H
